USE DWH
GO

-- Usuniêcie wymiaru czasu, jeœli ju¿ istnieje.
IF EXISTS (SELECT * FROM sys.objects WHERE name = 'DimTime' AND type = 'U')
BEGIN
    DROP TABLE DimTime;
END
GO

-- Tworzenie tabeli DimTime
CREATE TABLE DimTime (
    TimeID INT PRIMARY KEY,
    hour_val INT,
    minute_val INT,
	TimeFull Time
);

-- Wype³nianie tabeli DimTime wartoœciami od godziny 00:00 do 23:59
INSERT INTO DimTime (TimeID, hour_val, minute_val, TimeFull)
SELECT 
    (hour_vals.n * 60 + minute_vals.n) AS TimeID,
    hour_vals.n AS hour_val,
    minute_vals.n AS minute_val,
	CONVERT(TIME, CONCAT(hour_vals.n, ':', minute_vals.n, ':00')) AS TimeFull
FROM
    (SELECT 0 AS n UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9
	UNION SELECT 10 UNION SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15 UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19
	UNION SELECT 20 UNION SELECT 21 UNION SELECT 22 UNION SELECT 23) hour_vals
CROSS JOIN
    (SELECT 0 AS n UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9
	UNION SELECT 10 UNION SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15 UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19
	UNION SELECT 20 UNION SELECT 21 UNION SELECT 22 UNION SELECT 23
    UNION SELECT 24 UNION SELECT 25 UNION SELECT 26 UNION SELECT 27 UNION SELECT 28 UNION SELECT 29 UNION SELECT 30 UNION SELECT 31 UNION SELECT 32 UNION SELECT 33
    UNION SELECT 34 UNION SELECT 35 UNION SELECT 36 UNION SELECT 37 UNION SELECT 38 UNION SELECT 39 UNION SELECT 40 UNION SELECT 41 UNION SELECT 42 UNION SELECT 43
    UNION SELECT 44 UNION SELECT 45 UNION SELECT 46 UNION SELECT 47 UNION SELECT 48 UNION SELECT 49 UNION SELECT 50 UNION SELECT 51 UNION SELECT 52 UNION SELECT 53
    UNION SELECT 54 UNION SELECT 55 UNION SELECT 56 UNION SELECT 57 UNION SELECT 58 UNION SELECT 59) minute_vals;
